package com.example.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.SigRow
import com.example.ui.components.SigTagType
import com.example.ui.theme.*

@Composable
fun ReportEvidenceScreen(
    amount: Long,
    upiId: String,
    utr: String,
    txnId: String,
    maskPiiOn: Boolean,
    onToggleMask: () -> Unit,
    onConfirmFraudTriggerEmergency: () -> Unit,
    onBack: () -> Unit,
    onSpeakText: (String) -> Unit = {},
    onNavigateToAirGap: () -> Unit = {},
    initialTab: Int = 0,
    modifier: Modifier = Modifier
) {
    var selectedSectionTab by remember { mutableStateOf(initialTab) }
    val scrollState = rememberScrollState()
    var isPackGenerated by remember { mutableStateOf(false) }

    val displayUpi = if (maskPiiOn && upiId.length > 6) {
        "${upiId.take(4)}••••••@${upiId.substringAfter('@')}"
    } else upiId

    if (selectedSectionTab == 1) {
        CommunityScamAwarenessScreen(
            onBack = { selectedSectionTab = 0 },
            onSpeakText = onSpeakText,
            onNavigateToAirGap = onNavigateToAirGap,
            modifier = modifier
        )
        return
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(SatarkBg)
            .verticalScroll(scrollState)
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // Top Header
        Row(
            modifier = Modifier.fillMaxWidth(),
            verticalAlignment = Alignment.CenterVertically
        ) {
            IconButton(onClick = onBack, modifier = Modifier.testTag("m7_back_button")) {
                Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back", tint = SatarkInk)
            }
            Text(
                text = "M7 · Report & Evidence Pack",
                style = MaterialTheme.typography.titleMedium,
                color = SatarkInk,
                fontWeight = FontWeight.Bold
            )
            Spacer(modifier = Modifier.weight(1f))
            TextButton(onClick = onToggleMask) {
                Text(if (maskPiiOn) "👁 Masked ON" else "🔓 Full Raw", color = SatarkAccent, fontSize = 12.sp)
            }
        }

        // Section Tabs: Dossier Pack vs Koo Community
        TabRow(
            selectedTabIndex = selectedSectionTab,
            containerColor = SatarkPanel,
            contentColor = SatarkAccent
        ) {
            Tab(
                selected = selectedSectionTab == 0,
                onClick = { selectedSectionTab = 0 },
                text = { Text("Report Dossier", fontWeight = FontWeight.SemiBold, fontSize = 12.sp) },
                icon = { Icon(Icons.Default.Inventory2, contentDescription = null, modifier = Modifier.size(16.dp)) }
            )
            Tab(
                selected = selectedSectionTab == 1,
                onClick = { selectedSectionTab = 1 },
                text = { Text("Koo Community", fontWeight = FontWeight.SemiBold, fontSize = 12.sp) },
                icon = { Icon(Icons.Default.Groups, contentDescription = null, modifier = Modifier.size(16.dp)) }
            )
        }

        // Evidence Summary Card
        Card(
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = SatarkPanelCard),
            border = CardDefaults.outlinedCardBorder().copy(brush = androidx.compose.ui.graphics.SolidColor(SatarkBorder)),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(
                modifier = Modifier.padding(14.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = "INCIDENT DOSSIER SNAPSHOT",
                        style = MaterialTheme.typography.labelSmall,
                        color = SatarkAccent,
                        fontWeight = FontWeight.Bold,
                        letterSpacing = 1.sp
                    )
                    Surface(
                        shape = RoundedCornerShape(4.dp),
                        color = SatarkWarnAlpha
                    ) {
                        Text(
                            text = "USER-REPORTED",
                            fontSize = 9.sp,
                            fontWeight = FontWeight.Bold,
                            color = SatarkWarn,
                            modifier = Modifier.padding(horizontal = 6.dp, vertical = 2.dp)
                        )
                    }
                }

                Text(
                    text = "Self-reported incident record for 1930 cyber helpline and bank freeze request. Unverified by bank server.",
                    fontSize = 11.sp,
                    color = SatarkDim,
                    lineHeight = 15.sp
                )

                SigRow(label = "Reported Disputed Amount", value = "₹$amount", tagText = "Self-Reported", tagType = SigTagType.DANGER)
                SigRow(label = "Total Demanded by Suspect", value = "₹30,625", tagText = "3 Demands Logged", tagType = SigTagType.WARN)
                SigRow(label = "Suspect Beneficiary UPI", value = displayUpi, tagText = "Masked for Privacy", tagType = SigTagType.INFO)
                SigRow(label = "Bank UTR Number", value = utr, tagText = "Provided UTR", tagType = SigTagType.OK)
                SigRow(label = "UPI Transaction ID", value = txnId, tagText = "Reported Txn ID", tagType = SigTagType.OK)
                SigRow(label = "Suspect Shortlink", value = "cutt.ly/sec-upi-pay", tagText = "Phishing URL", tagType = SigTagType.WARN)
                SigRow(label = "Local File Integrity Hash", value = "SHA256: 8a3e7b...92e", tagText = "Export Checksum", tagType = SigTagType.INFO)
            }
        }

        // Pack Artifacts Blueprint
        Card(
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = SatarkPanelCard),
            border = CardDefaults.outlinedCardBorder().copy(brush = androidx.compose.ui.graphics.SolidColor(SatarkBorder)),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(
                modifier = Modifier.padding(14.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Text(
                    text = "DOSSIER ATTACHMENTS (COMPLAINT EXPORT)",
                    style = MaterialTheme.typography.labelSmall,
                    color = SatarkDim,
                    fontWeight = FontWeight.Bold,
                    letterSpacing = 1.sp
                )

                ArtifactRow("📦 case_analysis_bundle.zip", "Forensic archive: 22 verified scam cases & evidence crops in Downloads")
                ArtifactRow("📄 detailed_scam_case_explanations.pdf", "Official SANGYAN 2026 27MB case dossier in Downloads")
                ArtifactRow("📄 complaint_ncrp.md", "National Cyber Crime Reporting Portal ready text in Hindi & English")
                ArtifactRow("📧 complaint_email.eml", "Pre-formatted formal complaint to Cyber Cell & Bank Nodal Officer")
                ArtifactRow("📊 annexure.csv", "Detailed transaction timeline with hashes & suspect handles")
                ArtifactRow("📦 evidence_bundle.zip", "Tamper-evident ZIP archive with digital signatures & OCR proofs")
            }
        }

        // Community Shortcut Card
        Card(
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = SatarkAccentAlpha),
            border = CardDefaults.outlinedCardBorder().copy(brush = androidx.compose.ui.graphics.SolidColor(SatarkAccent)),
            modifier = Modifier
                .fillMaxWidth()
                .clickable { selectedSectionTab = 1 }
        ) {
            Row(
                modifier = Modifier.padding(14.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Icon(Icons.Default.Groups, contentDescription = null, tint = SatarkAccent, modifier = Modifier.size(24.dp))
                Column(modifier = Modifier.weight(1f)) {
                    Text("Koo Scam Community & Team Chat", fontWeight = FontWeight.Bold, color = SatarkInk, fontSize = 13.5.sp)
                    Text("Discuss latest scams with Prince Kumar Singh, Nishant & Kartik", fontSize = 11.sp, color = SatarkDim)
                }
                Icon(Icons.Default.ChevronRight, contentDescription = null, tint = SatarkAccent)
            }
        }

        // Pack Generation Action
        Button(
            onClick = { isPackGenerated = true },
            modifier = Modifier
                .fillMaxWidth()
                .height(48.dp)
                .testTag("generate_pack_button"),
            colors = ButtonDefaults.buttonColors(containerColor = SatarkAccent),
            shape = RoundedCornerShape(12.dp)
        ) {
            Icon(Icons.Default.Inventory2, contentDescription = null, tint = Color.White)
            Spacer(modifier = Modifier.width(8.dp))
            Text(
                text = if (isPackGenerated) "📦 Pack Ready (Saved Locally)" else "📦 Pack Banao (8 Seconds)",
                color = Color.White,
                style = MaterialTheme.typography.titleSmall,
                fontWeight = FontWeight.Bold
            )
        }

        Divider(color = SatarkBorder)

        // 🚨 CONFIRM FRAUD JUMP TO EMERGENCY
        Card(
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = SatarkDangerAlpha),
            border = CardDefaults.outlinedCardBorder().copy(brush = androidx.compose.ui.graphics.SolidColor(SatarkDanger)),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(
                modifier = Modifier.padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(Icons.Default.Emergency, contentDescription = null, tint = SatarkDanger)
                    Text(
                        text = "PAISA KAT GAYA HAI? (FRAUD CONFIRMED)",
                        style = MaterialTheme.typography.titleSmall,
                        color = SatarkDanger,
                        fontWeight = FontWeight.Bold
                    )
                }

                Text(
                    text = "Agar lagta hai fraud ho gaya hai, aur aap confirm karte hain — to turant Cyber Cell ko complaint mail bhejein aur helpline se payment stop karein.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = SatarkInk
                )

                Button(
                    onClick = onConfirmFraudTriggerEmergency,
                    colors = ButtonDefaults.buttonColors(containerColor = SatarkDanger),
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(52.dp)
                        .testTag("confirm_fraud_emergency_button"),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Icon(Icons.Default.Warning, contentDescription = null, tint = Color.White)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        text = "🚨 FRAUD CONFIRM → S9 Emergency Chalu Karo",
                        color = Color.White,
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold
                    )
                }
            }
        }
    }
}

@Composable
private fun ArtifactRow(title: String, subtitle: String) {
    Column {
        Text(text = title, style = MaterialTheme.typography.bodyMedium, color = SatarkInk, fontWeight = FontWeight.SemiBold)
        Text(text = subtitle, style = MaterialTheme.typography.bodySmall, color = SatarkDim, fontSize = 11.5.sp)
    }
}
